[package]
name = "wvx-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Dynamic playground runtime for WVX graphs"
publish.workspace = true

[dependencies]
thiserror = { workspace = true }
wvx-ir = { workspace = true }
wvx-types = { workspace = true }
wvx-validator = { workspace = true }

[lints]
workspace = true
