[package]
name = "wvx-component-sdk"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Adapter ABI for Gate F core-independent Loom implementations"
publish.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
wvx-types = { workspace = true }
wvx-runtime = { workspace = true }

[lints]
workspace = true
