//! Text emission for Cargo.toml, pipeline, main, lockfile.

use crate::adapters;
use crate::CompileError;
use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;
use wvx_ir::{PortPath, Project, SdkEmit};

pub fn cargo_toml(
    package_name: &str,
    impls: &BTreeSet<String>,
    sdk_emits: &BTreeMap<String, SdkEmit>,
) -> String {
    let mut deps = String::new();
    let mut seen_crates = BTreeSet::new();
    if adapters::needs_external_adapters(impls) {
        seen_crates.insert("wvx-adapters".to_string());
        deps.push_str("wvx-adapters = { path = \"vendor/wvx-adapters\" }\n");
        deps.push_str("serde_json = \"1\"\n");
    }
    for (impl_id, sdk) in sdk_emits {
        if !impls.contains(impl_id) {
            continue;
        }
        if !seen_crates.insert(sdk.crate_name.clone()) {
            continue;
        }
        let vendor_path = format!("vendor/{}", sdk.crate_name);
        deps.push_str(&format!(
            "{} = {{ path = \"{vendor_path}\" }}\n",
            sdk.crate_name
        ));
        if !deps.contains("serde_json") {
            deps.push_str("serde_json = \"1\"\n");
        }
    }
    format!(
        r#"[package]
name = "{package_name}"
version = "0.1.0"
edition = "2021"
publish = false
description = "Generated by Weavatrix Loom"

[dependencies]
{deps}
[[bin]]
name = "{package_name}"
path = "src/main.rs"

[lib]
name = "{package_name}"
path = "src/lib.rs"
"#
    )
}

/// Lockfile with policy id + optional resolution notes (Milestone 2).
pub fn lockfile_with_meta(
    project: &Project,
    resolved: &BTreeMap<String, String>,
    policy: &crate::CompilePolicy,
    resolutions: &[wvx_ir::ResolveDecision],
) -> String {
    let mut out = String::new();
    writeln!(out, "# WVX lockfile — exact implementations used for this export").ok();
    writeln!(out, "schema = {:?}", project.schema_version).ok();
    writeln!(out, "project = {:?}", project.id).ok();
    writeln!(out, "name = {:?}", project.name).ok();
    writeln!(out, "revision = {}", project.revision).ok();
    writeln!(out, "policy = {:?}", policy.id).ok();
    writeln!(out, "profile = {:?}", policy.target_profile.id).ok();
    writeln!(out, "allow_candidate = {}", policy.allow_candidate).ok();
    writeln!(out).ok();
    writeln!(out, "[instances]").ok();
    for (id, impl_id) in resolved {
        writeln!(out, "{id} = {impl_id:?}").ok();
    }
    if !resolutions.is_empty() {
        writeln!(out).ok();
        writeln!(out, "[resolution]").ok();
        for d in resolutions {
            let chosen = d.chosen.as_deref().unwrap_or("(none)");
            writeln!(
                out,
                "# {} → {}  (policy={}, profile={})",
                d.capability_key, chosen, d.policy_id, d.profile_id
            )
            .ok();
            for line in &d.explanation {
                writeln!(out, "#   {line}").ok();
            }
        }
    }
    out
}

pub fn main_rs() -> String {
    r##"//! Generated Loom binary.

mod generated_pipeline;

use std::env;
use std::io::{self, Write};

fn main() {
    let input = env::var("WVX_PIPELINE_INPUT")
        .map(|s| s.into_bytes())
        .or_else(|_| env::args().nth(1).map(|s| s.into_bytes()).ok_or(()))
        .unwrap_or_else(|_| br#"{"hello":"world"}"#.to_vec());

    match generated_pipeline::run_pipeline(&input) {
        // Raw bytes so binary domains (hash digests, gzip) round-trip in golden tests.
        Ok(bytes) => {
            let _ = io::stdout().write_all(&bytes);
        }
        Err(err) => {
            eprintln!("pipeline error: {err}");
            std::process::exit(1);
        }
    }
}
"##
    .into()
}

pub fn pipeline(
    project: &Project,
    order: &[String],
    resolved: &BTreeMap<String, String>,
    sdk_emits: &BTreeMap<String, SdkEmit>,
) -> Result<String, CompileError> {
    let mut out = String::new();
    writeln!(
        out,
        "// Generated by Weavatrix Loom from project `{}`",
        project.id
    )
    .ok();
    writeln!(
        out,
        "// Capability graph is fixed; implementations are selected at export time.\n"
    )
    .ok();
    writeln!(out, "// External adapters: dependency `wvx-adapters` (vendored).\n").ok();
    writeln!(
        out,
        "/// Run the exported pipeline. Input seeds the entrypoint `bytes` port."
    )
    .ok();
    writeln!(
        out,
        "pub fn run_pipeline(input: &[u8]) -> Result<Vec<u8>, String> {{"
    )
    .ok();

    // port values as rust vars: inst_port
    let mut port_vars: BTreeMap<String, String> = BTreeMap::new();
    let mut final_output: Option<String> = None;

    for instance_id in order {
        let instance = project
            .instance(instance_id)
            .ok_or_else(|| CompileError::Graph(format!("missing instance {instance_id}")))?;
        let cap_key = instance.capability.as_key();
        let impl_id = resolved
            .get(instance_id)
            .ok_or_else(|| CompileError::Graph(format!("unresolved impl for {instance_id}")))?;

        writeln!(out, "    // instance `{instance_id}`  capability `{cap_key}`  impl `{impl_id}`")
            .ok();

        if cap_key == "io.input.bytes@1" {
            let var = rust_var(instance_id, "bytes");
            writeln!(out, "    let {var}: Vec<u8> = input.to_vec();").ok();
            port_vars.insert(format!("{instance_id}.bytes"), var);
            continue;
        }

        if cap_key == "io.output.bytes@1" {
            // Find bound input
            let path = PortPath::new(instance_id, "bytes");
            let from = project
                .bindings
                .iter()
                .find(|b| b.to == path)
                .ok_or_else(|| {
                    CompileError::Graph(format!("output instance `{instance_id}` has no input"))
                })?;
            let src = port_vars
                .get(&from.from.to_string())
                .ok_or_else(|| {
                    CompileError::Graph(format!("missing source value for {}", from.from))
                })?
                .clone();
            final_output = Some(src);
            writeln!(out, "    // sink `{instance_id}`").ok();
            continue;
        }

        // Collect input expressions for this instance
        let mut input_exprs = BTreeMap::new();
        if let Some(cap) = project.capability_for(&instance.capability) {
            for input in &cap.inputs {
                let path = PortPath::new(instance_id, &input.id);
                let from = project
                    .bindings
                    .iter()
                    .find(|b| b.to == path)
                    .ok_or_else(|| {
                        CompileError::Graph(format!("unbound required input `{path}`"))
                    })?;
                let src = port_vars
                    .get(&from.from.to_string())
                    .ok_or_else(|| {
                        CompileError::Graph(format!("missing source for {}", from.from))
                    })?
                    .clone();
                input_exprs.insert(input.id.clone(), src);
            }
        }

        let config = serde_json::Value::Object(
            instance
                .config
                .iter()
                .map(|(k, v)| (k.clone(), v.clone()))
                .collect(),
        );

        let sdk = sdk_emits.get(impl_id.as_str());
        let call = adapters::emit_call(impl_id, &input_exprs, &config, sdk).map_err(|e| {
            CompileError::UnsupportedImplementation(impl_id.clone(), e)
        })?;

        // Determine output ports and types from capability
        let cap = project
            .capability_for(&instance.capability)
            .ok_or_else(|| CompileError::Graph(format!("unknown capability for {instance_id}")))?;

        if cap.outputs.len() == 1 {
            let port = &cap.outputs[0].id;
            let var = rust_var(instance_id, port);
            let ty = rust_type_for_port(&cap.outputs[0].ty);
            writeln!(out, "    let {var}: {ty} = {call};").ok();
            port_vars.insert(format!("{instance_id}.{port}"), var);
        } else if cap.outputs.is_empty() {
            writeln!(out, "    let _ = {call};").ok();
        } else {
            return Err(CompileError::Graph(format!(
                "multi-output instances not supported in v0.1 compiler ({instance_id})"
            )));
        }
    }

    let ret = final_output.ok_or_else(|| {
        CompileError::Graph(
            "no io.output.bytes sink found — cannot determine pipeline return value".into(),
        )
    })?;
    writeln!(out, "    Ok({ret})").ok();
    writeln!(out, "}}").ok();
    Ok(out)
}

fn rust_var(instance: &str, port: &str) -> String {
    let mut s = String::new();
    for ch in instance.chars() {
        if ch.is_ascii_alphanumeric() {
            s.push(ch);
        } else {
            s.push('_');
        }
    }
    s.push('_');
    for ch in port.chars() {
        if ch.is_ascii_alphanumeric() {
            s.push(ch);
        } else {
            s.push('_');
        }
    }
    if s.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        s.insert(0, '_');
    }
    s
}

fn rust_type_for_port(ty: &wvx_types::TypeRef) -> &'static str {
    use wvx_types::TypeRef;
    match ty {
        TypeRef::Bytes => "Vec<u8>",
        TypeRef::JsonValue => "serde_json::Value",
        TypeRef::String => "String",
        TypeRef::Bool => "bool",
        TypeRef::I64 => "i64",
        TypeRef::U64 => "u64",
        TypeRef::F64 => "f64",
        TypeRef::Unit => "()",
        _ => "serde_json::Value",
    }
}
