//! Export a validated WVX project as a readable Rust Cargo workspace skeleton.
//!
//! v0.1 emits orchestration stubs; real adapter calls land as implementations mature.

use serde::{Deserialize, Serialize};
use std::fmt::Write as _;
use thiserror::Error;
use wvx_ir::Project;
use wvx_validator::validate_project;

#[derive(Debug, Error)]
pub enum CompileError {
    #[error("project is not valid: {0}")]
    InvalidProject(String),
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GeneratedFile {
    pub relative_path: String,
    pub contents: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GeneratedWorkspace {
    pub files: Vec<GeneratedFile>,
}

/// Generate a Cargo workspace layout for the project.
pub fn compile_to_rust(project: &Project) -> Result<GeneratedWorkspace, CompileError> {
    let report = validate_project(project);
    if !report.is_ok() {
        let msg = report
            .errors()
            .map(|d| d.message.clone())
            .collect::<Vec<_>>()
            .join("; ");
        return Err(CompileError::InvalidProject(msg));
    }

    let mut files = Vec::new();

    files.push(GeneratedFile {
        relative_path: "Cargo.toml".into(),
        contents: format!(
            r#"[package]
name = "{pkg}"
version = "0.1.0"
edition = "2021"

[dependencies]
# Adapter crates are pinned by weavatrix.lock in a full export.
"#,
            pkg = sanitize_pkg_name(&project.id)
        ),
    });

    files.push(GeneratedFile {
        relative_path: "weavatrix.lock".into(),
        contents: format!(
            "# WVX lockfile (v0.1 scaffold)\nproject = {:?}\nschema = {:?}\ninstances = {}\n",
            project.id,
            project.schema_version,
            project.instances.len()
        ),
    });

    let mut pipeline = String::new();
    writeln!(
        pipeline,
        "// Generated by Weavatrix Loom from project `{}`",
        project.id
    )
    .ok();
    writeln!(pipeline, "// Do not edit by hand if you re-export from Loom.\n").ok();
    writeln!(pipeline, "pub fn run_pipeline(input: &[u8]) -> Result<Vec<u8>, String> {{").ok();
    writeln!(pipeline, "    // Instance order (declaration order in v0.1 scaffold):").ok();
    for instance in &project.instances {
        writeln!(
            pipeline,
            "    // - {}  ({})",
            instance.id,
            instance.capability.as_key()
        )
        .ok();
    }
    writeln!(
        pipeline,
        "    let _ = input;\n    Err(\"pipeline body not yet linked to adapters\".into())\n}}"
    )
    .ok();

    files.push(GeneratedFile {
        relative_path: "src/generated_pipeline.rs".into(),
        contents: pipeline,
    });

    files.push(GeneratedFile {
        relative_path: "src/main.rs".into(),
        contents: r##"mod generated_pipeline;

fn main() {
    match generated_pipeline::run_pipeline(br#"{"ok":true}"#) {
        Ok(bytes) => println!("{}", String::from_utf8_lossy(&bytes)),
        Err(err) => eprintln!("loom export scaffold: {err}"),
    }
}
"##
        .into(),
    });

    Ok(GeneratedWorkspace { files })
}

fn sanitize_pkg_name(id: &str) -> String {
    let mut out = String::new();
    for ch in id.chars() {
        if ch.is_ascii_alphanumeric() {
            out.push(ch.to_ascii_lowercase());
        } else {
            out.push('_');
        }
    }
    if out.is_empty() || out.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        out.insert_str(0, "wvx_");
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use wvx_ir::{Capability, CapabilityRef, Instance, PortSpec, PROJECT_SCHEMA_VERSION};
    use wvx_types::TypeRef;

    #[test]
    fn emits_main_and_pipeline() {
        let mut p = Project::new("demo_app", "Demo");
        p.schema_version = PROJECT_SCHEMA_VERSION.into();
        p.capabilities.push(Capability {
            id: "io.input.bytes".into(),
            version: "1".into(),
            kind: "io".into(),
            inputs: vec![],
            outputs: vec![PortSpec {
                id: "bytes".into(),
                ty: TypeRef::Bytes,
                required: true,
            }],
            errors: vec![],
            effects: vec![],
        });
        p.instances.push(Instance {
            id: "input".into(),
            capability: CapabilityRef::new("io.input.bytes", "1"),
            implementation: None,
            config: Default::default(),
            ui: None,
        });
        p.entrypoint = Some("input".into());
        let ws = compile_to_rust(&p).unwrap();
        assert!(ws.files.iter().any(|f| f.relative_path == "src/main.rs"));
        assert!(ws
            .files
            .iter()
            .any(|f| f.relative_path == "src/generated_pipeline.rs"));
    }
}
