[package]
name = "wvx-validator"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Structural and type validation for WVX projects"
publish = true
keywords = ["weavatrix", "loom", "wvx"]
categories = ["development-tools"]
readme = "README.md"

[dependencies]
serde = { workspace = true }
wvx-ir = { workspace = true }
wvx-types = { workspace = true }

[lints]
workspace = true
