[package]
name = "wvx-ir"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "WVX intermediate representation for Weavatrix Loom projects"
publish.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
wvx-types = { workspace = true }

[lints]
workspace = true
